# Generated by Django 2.1.3 on 2019-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='Никто', max_length=30)),
                ('vac_start', models.DateField(default='2018-01-01', null=True)),
                ('vac_dur', models.PositiveIntegerField(default=14, null=True)),
                ('vac_end', models.DateField(default='2018-01-14')),
            ],
        ),
    ]
