# Generated by Django 2.1.3 on 2019-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190517_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vsc_status',
            field=models.IntegerField(default=0),
        ),
    ]
