# Generated by Django 2.1.3 on 2019-05-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190523_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='vac_status',
            field=models.CharField(max_length=100),
        ),
    ]
